apiVersion: v1
kind: ConfigMap
metadata:
  name: casinoshiz-grafana-clickhouse-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  clickhouse.yaml: |
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        access: proxy
        uid: clickhouse
        isDefault: false
        url: http://clickhouse.data.svc.cluster.local:8123
        jsonData:
          host: clickhouse.data.svc.cluster.local
          port: 9000
          protocol: native
          defaultDatabase: cazinoshiz
          username: default
        secureJsonData:
          password: ${CLICKHOUSE_PASSWORD}
