apiVersion: v1
kind: Secret
metadata:
    name: grafana-clickhouse-secret
    namespace: monitoring
type: Opaque
stringData:
    clickhouse-password: ENC[AES256_GCM,data:a5egvHtjU3sq,iv:wY8qdugBYVU2ikSV54rSJmU+Cu3gShXYsoIXVKLQxcU=,tag:RObFo2H42wJGc+WSfL5HHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ0FtY0ZFQ0xUSjhtajdh
            c1FHZzlQcWRDUDdoemdManZBaU1tVGo0dmo4CjRJamdtUDE1dzl6RDBFeldTR2dv
            OHNrMWNBL2JVelNGczd4aHRlUVorNm8KLS0tIFU1NnZrSGRaMVFVTUxrQnF2VnBq
            SVZtbTFsNk5vK0NHdlFONlZCUCtPcDQK0pcvVWkfV4/Ov5Vf+sgGpWAYiMA/X3H0
            Mlx/WPUdurebw1sbHroVIsmgdXy1KeragtlqI/vEkz5rboER+SAdVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12rjygp23vmnu2tnl5hsf2qh2pqp4ym775vad3fp5qdrs2q9ldcxqqpgnqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:38:03Z"
    mac: ENC[AES256_GCM,data:nVdPztzoQgNgwZq7oOcy/oIjEyk5tKvZDPz2dZXMmEGnIHCjBukXzHmWlCYJDJoAHiOv/UCZ/syIY7v5qvrLE1j8AngCVaJGKWV7Qf+9icMtpR9j2SuqCdkH1JotDrtfHqRztnx7CoAEsM+9OG+ys0Alqzj33uyLeTb+lSv9LGc=,iv:x5gST1jh8OWgSR8oc8NwPFE18KFGCNmd68vd2t5hmrE=,tag:eSngQKW1WZrV6n+ABHLQzQ==,type:str]
    version: 3.13.2
