apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rules.yaml
  - scrapes.yaml
  - vmagent-config-rbac.yaml
  - clickhouse-datasource.yaml
  - grafana-clickhouse.secret.yaml
  - dashboards
