apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: casinoshiz
  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: data
    plugin:
      name: sops-kustomize-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
