apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform/namespaces
  - ../../platform/cert-manager
  - ../../platform/keda
  - ../../platform/monitoring
  - ../../platform/tracing
  - ../../platform/network-policies
  - ../../data
  - ./casinoshiz
