{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: casinoshiz-secrets
type: Opaque
stringData:
  backend-postgres-connection-string: CHANGE_ME
  identity-postgres-connection-string: CHANGE_ME
  wallet-postgres-connection-string: CHANGE_ME
  redis-connection-string: CHANGE_ME
  operations-api-key: CHANGE_ME
{{- end }}
