{{- if .Values.monitoring.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: casinoshiz
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  selector:
    matchLabels:
      app.kubernetes.io/part-of: casinoshiz
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
