apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-casinoshiz-bot2-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: casinoshiz
  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: platform/bot2/data
  destination:
    server: https://kubernetes.default.svc
    namespace: casinoshiz-bot2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      namespace: casinoshiz-bot2
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.podManagementPolicy
        - .spec.updateStrategy
        - .spec.revisionHistoryLimit
        - .spec.template.metadata.creationTimestamp
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.securityContext
        - .spec.template.spec.containers[].imagePullPolicy
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .spec.template.spec.containers[].ports[].protocol
        - .spec.template.spec.containers[].readinessProbe.successThreshold
        - .spec.template.spec.containers[].livenessProbe.successThreshold
        - .spec.template.spec.containers[].startupProbe.successThreshold
        - .spec.template.spec.containers[].readinessProbe.timeoutSeconds
        - .spec.template.spec.containers[].livenessProbe.timeoutSeconds
        - .spec.template.spec.containers[].startupProbe.timeoutSeconds
        - .spec.volumeClaimTemplates[].metadata.creationTimestamp
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
        - .spec.volumeClaimTemplates[].status
        - .spec.volumeClaimTemplates[].spec.volumeMode
    - group: external-secrets.io
      kind: ExternalSecret
      name: casinoshiz-bot2-secrets
      namespace: casinoshiz-bot2
      jqPathExpressions:
        - .metadata.annotations["force-sync"]
        - .spec.dataFrom[].extract.conversionStrategy
        - .spec.dataFrom[].extract.decodingStrategy
        - .spec.dataFrom[].extract.metadataPolicy
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy
