apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-casinoshiz-bot2-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: casinoshiz
  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: platform/bot2/data
  destination:
    server: https://kubernetes.default.svc
    namespace: casinoshiz-bot2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      name: casinoshiz-bot2-secrets
      namespace: casinoshiz-bot2
      jqPathExpressions:
        - .metadata.annotations["force-sync"]
