apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-casinoshiz-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: casinoshiz

  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: master
    path: .
    plugin:
      name: sops-kustomize-v1.0
      env:
        - name: KUSTOMIZE_PATH
          value: clusters/local/stages/app

  destination:
    server: https://kubernetes.default.svc
    namespace: casinoshiz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
