apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-casinoshiz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: casinoshiz
  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: charts/casinoshiz
    helm:
      releaseName: casinoshiz
      valueFiles: [values-local.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: casinoshiz
  syncPolicy:
    automated: { prune: true, selfHeal: false }
    syncOptions: [CreateNamespace=true, PruneLast=true, ServerSideApply=true]
