apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"

spec:
  project: casinoshiz

  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: .
    plugin:
      name: sops-kustomize-v1.0
      env:
        - name: KUSTOMIZE_PATH
          value: clusters/local/stages/data

  destination:
    server: https://kubernetes.default.svc
    namespace: data

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      namespace: data
      jqPathExpressions:
        - .spec.podManagementPolicy
        - .spec.updateStrategy
        - .spec.revisionHistoryLimit
        - .spec.template.metadata.creationTimestamp
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.securityContext
        - .spec.template.spec.containers[].imagePullPolicy
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .spec.template.spec.containers[].ports[].protocol
        - .spec.template.spec.containers[].readinessProbe.successThreshold
        - .spec.template.spec.containers[].livenessProbe.successThreshold
        - .spec.template.spec.containers[].startupProbe.successThreshold
        - .spec.volumeClaimTemplates[].metadata.creationTimestamp
        - .spec.volumeClaimTemplates[].spec.volumeMode

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
