apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-monitoring-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: casinoshiz
  source:
    repoURL: https://github.com/cpp20120/CasinoShiz.Infrastructure.git
    targetRevision: main
    path: platform/monitoring
    plugin:
      name: sops-kustomize-v1.0
      env:
        - name: KUSTOMIZE_PATH
          value: .
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: operator.victoriametrics.com
      kind: VMRule
      name: casinoshiz-platform
      namespace: monitoring
      jqPathExpressions:
        - .spec.groups[].rules[].record
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
