apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: casinoshiz
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: '*'
    helm:
      releaseName: opentelemetry-collector
      valuesObject:
        mode: deployment
        replicaCount: 1
        image:
          repository: otel/opentelemetry-collector-contrib
        command:
          name: otelcol-contrib
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          processors:
            memory_limiter:
              check_interval: 5s
              limit_percentage: 75
              spike_limit_percentage: 15
            batch: {}
          exporters:
            prometheus:
              endpoint: 0.0.0.0:8889
              resource_to_telemetry_conversion:
                enabled: true
            otlp/tempo:
              endpoint: tempo.observability.svc.cluster.local:4317
              tls:
                insecure: true
          service:
            pipelines:
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [prometheus]
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/tempo]
        ports:
          otlp:
            enabled: true
          otlp-http:
            enabled: true
          metrics:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            protocol: TCP
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
