apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: casinoshiz
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: '*'
    helm:
      releaseName: vault
      valuesObject:
        injector:
          enabled: true
        server:
          dev:
            enabled: true
            devRootToken: root
          dataStorage:
            enabled: false
          auditStorage:
            enabled: false
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
