apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: casinoshiz
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: admin-password
      remoteRef:
        key: casinoshiz/sso
        property: admin-password
    - secretKey: postgres-password
      remoteRef:
        key: casinoshiz/sso
        property: postgres-admin-password
    - secretKey: password
      remoteRef:
        key: casinoshiz/sso
        property: postgres-password
    - secretKey: grafana-client-secret
      remoteRef:
        key: casinoshiz/sso
        property: grafana-client-secret
    - secretKey: argocd-client-secret
      remoteRef:
        key: casinoshiz/sso
        property: argocd-client-secret
    - secretKey: sso-admin-user
      remoteRef:
        key: casinoshiz/sso
        property: sso-admin-user
    - secretKey: sso-admin-password
      remoteRef:
        key: casinoshiz/sso
        property: sso-admin-password
