global:
  secretName: casinoshiz-bot2-secrets-vault

services:
  telegram-bff:
    host: tg2.casinoshiz.localhost
  admin-bff:
    host: admin2.casinoshiz.localhost
  rest-api:
    host: api2.casinoshiz.localhost
