apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
  values:
    replicas: 1
    tempo:
      reportingEnabled: false
      retention: 168h
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
    persistence:
      enabled: true
      storageClassName: local-path
      size: 20Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "2"
        memory: 2Gi
    service:
      type: ClusterIP
