- name: Ensure k3s configuration directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Render k3s configuration
  ansible.builtin.template:
    src: ../templates/k3s-config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0600"
  notify: Restart k3s
