global:
  domain: argocd.CHANGE_ME
configs:
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hostname: argocd.CHANGE_ME
    tls: true
repoServer:
  volumes:
    - name: cmp-plugin
      configMap:
        name: argocd-cmp-sops-kustomize
    - name: sops-age
      secret:
        secretName: sops-age
    - name: custom-tools
      emptyDir: {}
    - name: cmp-tmp
      emptyDir: {}
  initContainers:
    - name: install-tools
      image: alpine:3.22
      command: [/bin/sh, -ec]
      args:
        - |
          apk add --no-cache curl tar
          curl -fsSL https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64 -o /custom-tools/sops
          chmod +x /custom-tools/sops
          curl -fsSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz | tar -xz -C /custom-tools
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
  extraContainers:
    - name: cmp-sops-kustomize
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v3.4.5
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /sops-age/keys.txt
        - name: PATH
          value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-tmp
          mountPath: /tmp
        - name: cmp-plugin
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: plugin.yaml
        - name: sops-age
          mountPath: /sops-age
          readOnly: true
        - name: custom-tools
          mountPath: /custom-tools
          readOnly: true
