apiVersion: v1
kind: Secret
metadata:
    name: casinoshiz-secrets
    namespace: casinoshiz
type: Opaque
stringData:
    backend-postgres-connection-string: ENC[AES256_GCM,data:U1FSg+Hjxw7FbYxjPXmZ4QG8IoE7f5VdeqB37GNwIriXVPSdK3jIVx/dyB7rQ/JvIyh+cSFJiALKoHDQU9cf+ipOFFAkAHtc5SlklMn5eCK7LeC6z4ZBPVpdQ/Vbn87DeSQS,iv:0eYzN9HtuTl5mV+jrhXQmbjlcs7LyPZuW1FouE+tzLs=,tag:bSPm3FaYK2uHSLLw+NumNQ==,type:str]
    identity-postgres-connection-string: ENC[AES256_GCM,data:fRDKKM3z/jcKVo3+StGSU/F2uRGPQ/0VIj8Unike+0nUtFh+lIlPzAujOA6OX5jRtqD40JuD+upLvv5/Vl/efcBKWjTf7tDmRBADOX1AtZegRkGrzRloU4Fz+0CPhIjX3l3xN9I=,iv:3Ox7bM8aqbIAEtVmmi8auYp4TQI47rceMhDV1jimGHw=,tag:1j226nDBgHdPdcvh+1rHSQ==,type:str]
    wallet-postgres-connection-string: ENC[AES256_GCM,data:iWO7trFCSCfP8+YVcg7ofjsAOJqtoQb7WkBO46WJqnZWVjB94zKcR6Ls13WfqwgfZWzgM2JCPQlHauBYOEFeAX4oSIgqj0SQ15c8C8wKpsWpyG2IhmUd3Z0ly1GEqN1qEg==,iv:Y2BJ0DpinhzNgWSUi6LbpqX0yWvVLsotH+6LlRRRzGg=,tag:MoTBBHO6y1OM44mewtTx/Q==,type:str]
    redis-connection-string: ENC[AES256_GCM,data:HXkR6Gccp992XbN5hlNImMSIYbwN1G00GPRWJc3+Q/Y1uISCymOxdJS9M5AFm+PYjuoy8Q==,iv:Na/bsDrTrE0pJG5GWcpypuwpycvh7zPskqw8EPsngaU=,tag:V5PNNtk72C/1xuUuGJO9XQ==,type:str]
    operations-api-key: null
    #ENC[AES256_GCM,data:3JRnofYVx0kOR28INwp6YyDK+G75Fp5pHABQ4kMJ3n8YLqZVZVnLV933sBNznLRoz6DE1joGDuR7q70vh/4na5wSbIjq838=,iv:3Nqga1tC8BY2Yf7SidCNPzlaaa77Svg2g/pK0IQ/+PI=,tag:Ttq5T6caYAeFteKp1ojv2g==,type:comment]
    telegram-bot-token: ENC[AES256_GCM,data:lxa031HhQP0jeLS/TN9jQXA/r5Criaawsh6+A485mDONxScpNlqtKbQhTeEwgA==,iv:rGNIPPcKkAnPlKBMrnBbTym34wxgmt1nb81mQcuYwBM=,tag:5dsGyyC4siEVrufRJT84wA==,type:str]
    admin-web-token: ENC[AES256_GCM,data:kRnYNJdm0MRphwNUPXhh0WtLoBgZhZASOc4bcBGEGC2IC8CQ8DV2YWew4HGXR2Sv0Onz/j4rR1d2uNwaYjbNmA==,iv:LaDmY7D6e6TlsyP1OIAJi3FCBjWqJmsRMS084B/QI9k=,tag:COF76gHgJtx4N+sYU8bNsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y0Jid3dpcGVVNDEwQzgx
            YzBvVXo0NTRIaGpEcFVrVkorYm1MYkZwa25NClNIRXBTaldpd0lSUWJpMWt0aFFB
            NjhSRXdhdExRZ3RqRkw4YWg2SUdlZzgKLS0tIDBIdlVFNnVPUExTYmZJMHl0Y0VZ
            OEQxbEZyWk5iL2hURjRJK0JldGlXdFUKHb0rP42maMHwXThs9UUxEBIQ+cEII1OH
            b+sdk6g1OI5oUKD84XT4M9v9tle6wVs/SL+DlAwP9jZoUDp427fa0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12rjygp23vmnu2tnl5hsf2qh2pqp4ym775vad3fp5qdrs2q9ldcxqqpgnqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T15:47:00Z"
    mac: ENC[AES256_GCM,data:egaJRJGhJhLQZ0sRIvbqxHLmYjHg2hFoyWmDtizNuWysWISRwFri2uBjLJ96o23WM8nrz8LncKDSejJbNBVVfyVzznScs0KEL3z0pDdcYgpF0ZGqmXM3TmRBOLGTloS7C56f8DVXItzEVRrlyhjWmC5cjfjuLg/qUtS8QYShftc=,iv:XeBYIPXXPjv08jxa+IukyhM2pdXfySqloGAN/cliLNo=,tag:HsXO7BHzrUNqIjAeDXIT9w==,type:str]
    version: 3.13.2
