apiVersion: v1
kind: Secret
metadata:
    name: casinoshiz-secrets
    namespace: casinoshiz
type: Opaque
stringData:
    backend-postgres-connection-string: ENC[AES256_GCM,data:Jd2wmCF0sLoYpw5hTqRwxjcph6PisXznic2A0OSDloqUca5LhzvvwqzDnr02KPyg/HFjItVdDMK+9S3E5t6YMd5aXukk0oLIzl/XZ/Km3g7OE4BVQPLPHU3FOqwgttXTjPeEIm44+GPIGzUG+xafa4S7X43nASe905KvKX5UJ43xwThjVqbfzYxskikcMZYPg74ciGR8,iv:lKceiyfA0a7owdmPKv7DVBAWHyejvBUKIG/6xli/Ok4=,tag:Z9PG5CJoxkL4eeC5MOKMKw==,type:str]
    identity-postgres-connection-string: ENC[AES256_GCM,data:S/ObUCzx1gAUj3jxLz7x1SGkL4O7ZVwwlFUYRwlY9n/K0vd4lOnVWvJqrWIBK6dOiwJWSjUApOAAO+6keWuaw5205aNRZ9gmIHznzHYmsGkHlx3VhMHjJnmAd8bH0ABw1HrNjbK8VfltRbtDlEwo7Wi9a9OzxIbbjqwNtYa0Np4UeG6g/v7eBoqGYqXvusqpvFUwyErmj58=,iv:Rvkk+s4aX+8jdrleZ7soGTmxacytmBiVBL6VC+XUpmE=,tag:bnR1jOgtvGuxVh5zXcX5jQ==,type:str]
    wallet-postgres-connection-string: ENC[AES256_GCM,data:3ij03B0lGmwc76YccXCO+LABbq+KY3BZpsnfBdr1OZsWiHTqkJnwHvt0XnsI2pVPw2OiNlpwKZs9MR4DTb3d0LmBtd/FKoP3LRegXy3pM4C9hGkti+NrE3OB5/FeONuKthBDjfcCSzSP8lQ1Q/U3lcGGC2YuH2j0wFXluJbpgKZXAKJlkGqpNiAS1Jr1qP3ih9uSfg==,iv:KPfxHzXcGUi+u2Rk4DkhSwFHxT9it/mlltHwouQgks8=,tag:tBU5TPeMpwttXMvzGRjNqA==,type:str]
    redis-connection-string: ENC[AES256_GCM,data:HXkR6Gccp992XbN5hlNImMSIYbwN1G00GPRWJc3+Q/Y1uISCymOxdJS9M5AFm+PYjuoy8Q==,iv:Na/bsDrTrE0pJG5GWcpypuwpycvh7zPskqw8EPsngaU=,tag:V5PNNtk72C/1xuUuGJO9XQ==,type:str]
    operations-api-key: ENC[AES256_GCM,data:QzSgZrpIPYePKStmK7DdhqstIzbMHJ/+kASv7WfO5jGR5AsQHdPf6xbmGY3RDq7bNt+r/2tI8Cq997yPRi9YFA==,iv:Ru3ECF/2ByiT8rvqFoRUZgTaMBthbdxSZD2aMaEV9Qc=,tag:QbaKY58qxcixdnVYDThWIA==,type:str]
    #ENC[AES256_GCM,data:3JRnofYVx0kOR28INwp6YyDK+G75Fp5pHABQ4kMJ3n8YLqZVZVnLV933sBNznLRoz6DE1joGDuR7q70vh/4na5wSbIjq838=,iv:3Nqga1tC8BY2Yf7SidCNPzlaaa77Svg2g/pK0IQ/+PI=,tag:Ttq5T6caYAeFteKp1ojv2g==,type:comment]
    telegram-bot-token: ENC[AES256_GCM,data:lxa031HhQP0jeLS/TN9jQXA/r5Criaawsh6+A485mDONxScpNlqtKbQhTeEwgA==,iv:rGNIPPcKkAnPlKBMrnBbTym34wxgmt1nb81mQcuYwBM=,tag:5dsGyyC4siEVrufRJT84wA==,type:str]
    admin-web-token: ENC[AES256_GCM,data:kRnYNJdm0MRphwNUPXhh0WtLoBgZhZASOc4bcBGEGC2IC8CQ8DV2YWew4HGXR2Sv0Onz/j4rR1d2uNwaYjbNmA==,iv:LaDmY7D6e6TlsyP1OIAJi3FCBjWqJmsRMS084B/QI9k=,tag:COF76gHgJtx4N+sYU8bNsg==,type:str]
    clickhouse-password: ENC[AES256_GCM,data:iYbOUMscZ2jX,iv:D6CUCiNwTnHgWQv8dskyIJLhN9AWfkyX8artBowTc3M=,tag:fZ/JOsy1JX1pIUJ0ZDTTFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y0Jid3dpcGVVNDEwQzgx
            YzBvVXo0NTRIaGpEcFVrVkorYm1MYkZwa25NClNIRXBTaldpd0lSUWJpMWt0aFFB
            NjhSRXdhdExRZ3RqRkw4YWg2SUdlZzgKLS0tIDBIdlVFNnVPUExTYmZJMHl0Y0VZ
            OEQxbEZyWk5iL2hURjRJK0JldGlXdFUKHb0rP42maMHwXThs9UUxEBIQ+cEII1OH
            b+sdk6g1OI5oUKD84XT4M9v9tle6wVs/SL+DlAwP9jZoUDp427fa0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12rjygp23vmnu2tnl5hsf2qh2pqp4ym775vad3fp5qdrs2q9ldcxqqpgnqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T10:02:29Z"
    mac: ENC[AES256_GCM,data:QdIM2pp/kStKLz6v8CvK7sBHT6ci4gxqmgfq3dijNrYRZA8Kpjfq3QgztIoLzL0fy+V9izSqeBBP4/+eVCHfGYqX+j8zi41uGQKdQle/pSJOjPVysgmGNG+AiPYCKZdhwhOzTh3kuCoehHVghVuRscz7fx83o8xHp9M8hJ0Kfs0=,iv:Ws2FVYDk74TDRNlNJyT0TywpRIiuCHdJFnoP+imDQxU=,tag:rGS+mi68nX0oHKPDENGYOA==,type:str]
    version: 3.13.2
