apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: casinoshiz
  namespace: casinoshiz
spec:
  interval: 2m
  chart:
    spec:
      chart: ./charts/casinoshiz
      sourceRef:
        kind: GitRepository
        name: casinoshiz-infrastructure
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: casinoshiz-local-values
      valuesKey: values.yaml
