apiVersion: v1
kind: ConfigMap
metadata:
  name: casinoshiz-production-values
  namespace: casinoshiz
data:
  values.yaml: |
    global:
      imageRegistry: ghcr.io/cpp20120

    backendImage:
      repository: casinoshiz-backend
      tag: CHANGE_ME

    services:
      identity:
        image:
          repository: casinoshiz-identity
          tag: CHANGE_ME
      wallet:
        image:
          repository: casinoshiz-wallet
          tag: CHANGE_ME
      telegram-bff:
        image:
          repository: casinoshiz-telegram-bff
          tag: CHANGE_ME
        host: tg.CHANGE_ME
      discord-bff:
        image:
          repository: casinoshiz-discord-bff
          tag: CHANGE_ME
      admin-bff:
        image:
          repository: casinoshiz-admin-bff
          tag: CHANGE_ME
        host: admin.CHANGE_ME
      rest-api:
        image:
          repository: casinoshiz-rest-api
          tag: CHANGE_ME
        host: api.CHANGE_ME

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 65
