apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml
configMapGenerator:
  - name: ingress-profile
    namespace: casinoshiz
    literals:
      - name=nginx
generatorOptions:
  disableNameSuffixHash: true
