apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: casinoshiz-secrets
  namespace: casinoshiz
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: casinoshiz-secrets-vault
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: casinoshiz/app
